software_groups: &software
  - "base"

packages:
  branch_codenames:
    master: trusty-unstable
    production: trusty-stable

jobs:
  varnish:
    builder: "make"
    base: "quay.io/madebymany/build-bases:trusty"
    software_groups: *software
    packages:
      - type: debian
        name: varnish
        version: 4.0.10-2
        depends:
          - "libedit-dev"
          - "libncurses-dev"
          - "libpcre3-dev"
          - "runit"
        target: install
        repos:
          - composed-public
        activates:
          - varnish-upgrade
