software_groups: &software
  - "base"

packages:
  branch_codenames:
    master: unstable
    production: stable

jobs:
  varnish:
    builder: "make"
    base: "ubuntu:12.04"
    software_groups: *software
    packages:
      - type: debian
        name: varnish
        version: 4.0.10-1
        depends:
          - "libedit-dev"
          - "libncurses-dev"
          - "libpcre3-dev"
          - "runit"
        target: install
        repos:
          - composed-public
        activates:
          - varnish-upgrade
