#!/bin/sh

exec 2>&1

DAEMON=/usr/local/sbin/varnishd

if [ -f /etc/default/varnish ] ; then
    . /etc/default/varnish
fi

DAEMON_OPTS=${DAEMON_OPTS:--b localhost}

# Open files (usually 1024, which is way too small for varnish)
ulimit -n ${NFILES:-131072}

# Maxiumum locked memory size for shared memory log
ulimit -l ${MEMLOCK:-82000}

# Ensure we have a PATH
export PATH="${PATH:+$PATH:}/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin"

exec ${DAEMON} ${DAEMON_OPTS}
